### ISSUE TITLE
Retina Support

### ISSUE THREAD

**Issue by dubiousdavid** [oakes/Nightcode#111]
Just downloaded 0.4.0 from the App Store and noticed that you don’t have retina display support.

**Comment by amekusa** [comment]
To activate retina support on OSX apps, the following key may have to be specified as true in `info.plist`.

```xml
<key>NSHighResolutionCapable</key>
<true/>
```
http://www.xojo.com/blog/en/2014/07/adding-plist-settings-to-your-os-x-apps.php

**Comment by oakes** [comment]
@amekusa Thank you very much for pointing that out. I added that to the latest versions of Nightcode and Nightmod on the app store.
