### ISSUE TITLE
App Store version does not present ios "Run ... Build ... RoboVM" pane 

### ISSUE THREAD

**Issue by davidrupp** [oakes/Nightcode#123]
Created new Game project from template in both App Store and standalone versions, both at version 0.4.3. Having clicked on the ios folder in the project pane, the standalone version has all of the run options, plus the red RoboVM button. Same sequence on the App Store version, but the entire pane is empty. I'm happy to spend some time researching this, if you'll give me a pointer to where the behaviors might start diverging.

**Comment by oakes** [comment]
Yeah this is intentional. Due to app sandboxing, I wasn't able to successfully get that functionality to work. I used to provide a disclaimer about this in the app description as well as in the app itself, but Apple forced me to remove them. Sorry about this.

**Comment by davidrupp** [comment]
So I can't use the App Store version to build iOS apps?

**Comment by oakes** [comment]
Correct. I'll spend more time trying to fix the sandbox issue, but for now or isn't possible.
