### ISSUE TITLE
[questions] clojure.tools.nrepl.transport.Transport and aws/sdk/s3.clj

### ISSUE THREAD

**Issue by birdspider** [oakes/Nightcode#124]
I wanted to try to make the nightcode repl compatible with this repl beautifier:
https://github.com/venantius/ultra -  which (among other things) prints shell color codes. 

Like so:

![nightcode_ultra_repl](https://cloud.githubusercontent.com/assets/370960/6553362/41b38cb8-c650-11e4-8c65-d65bad1cb1de.png)

I pulled my fork, synced, did some cleanups, but whenever I "Run in Repl" I get the following exception. 

````
Running with REPL...
nREPL server started on port 58879 on host 127.0.0.1 - nrepl://127.0.0.1:58879
Exception in thread "nREPL response poller" java.lang.NoClassDefFoundError: clojure/tools/nrepl/transport/Transport
````

![nightcode_ultra_repl_gitfail](https://cloud.githubusercontent.com/assets/370960/6553363/41b38952-c650-11e4-9d86-7778252b8b55.png)

Do you have any idea why basicly the same (codewise) nightcode launches would behave differently regarding this Exception.

Also `nightcode$ lein run`complains about missing `aws/sdk/s3.clj on classpath`, why is it excluded in project.clj ?

**Comment by birdspider** [comment]
By the way, thats how an exception looks like with ultra:
![wish](https://cloud.githubusercontent.com/assets/370960/6554013/236056b8-c657-11e4-9960-7d36e47ab617.png)

**Comment by oakes** [comment]
My guess is that the error is caused by conflicting versions of tools.nrepl being brought in. Nightcode includes Leiningen 2.5.1, which brings in tools.nrepl 0.2.6. This ultra library brings in tools.nrepl 0.2.7. If you add `:exclusions [org.clojure/tools.nrepl]` to the vector in which you are bringing in ultra, it might work.

Regarding the aws exclusion, that's because the aws sdk is very large and would balloon the jar file size if I included it. I'm not sure why the error is happening but hopefully the aforementioned solution will also fix that. Let me know if you still have issues after trying it.

**Comment by birdspider** [comment]
So, it (the nrepl strangeness) stopped happening, I assume because I disable a few ./lein/profiles.clj plugins:
````
{:user {
  :plugins [
    ;[lein-try "0.4.3"]
    ;[lein-localrepo "0.5.3"]
    [venantius/ultra "0.3.2"]
    ;[lein-ancient "0.6.4"]
    ;[lein-kibit "0.0.8"]]
  :ultra {:color-scheme :solarized_dark}}}
````
Further I tweaked nightcode.ui.JConsole.java a bit to drop ANSI Escape Codes. 
This enables me to use 'venantius/ultra' without having to fiddle with its config to much (since I wanted it always on).

The benefit of this in nightcode is that instead of i.e. :
````
ClassCastException java.lang.Class cannot be cast to java.lang.Throwable  \
  play.core.desktop-launcher/x (desktop_launcher.clj:12)
````
you would get:
````
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.Throwable
       play.core.desktop-launcher/x  form-init1136070863867463479.clj:    1
       play.core.desktop-launcher/y  form-init1136070863867463479.clj:    1
       play.core.desktop-launcher/z  form-init1136070863867463479.clj:    1
play.core.desktop-launcher/eval4590  form-init1136070863867463479.clj:    1
                                ...                                        
                  clojure.core/eval                          core.clj: 2927
````

I am content with how this works and will not attemt to colorize those ANSI codes in nightcode.
So I assume I can close this.
