### ISSUE TITLE
ClassNotFoundException clojure.set

### ISSUE THREAD

**Issue by jarcane** [oakes/Nightcode#126]
I was working through the I-love-ponies course today (the structured-data section here: https://github.com/jarcane/structured-data), and ran into an issue where the call to clojure.set/union was causing an exception when I ran the tests, ie: 

`Exception in thread "main" java.lang.ClassNotFoundException: clojure.set, compiling:(structured_data.clj:98:3)`

I don't have this issue when I run my tests in a local command line window with `lein midje`, nor do I run into this in Light Table, nor if I eval the sample exercise definitions and test my function in the repl. It only does it when I run the tests.

I also get the same exception if I try using `clojure.set/union` in the scratch REPL box on the lower left:

```
user=> (clojure.set/union #{1 2 3} #{3 4})
ClassNotFoundException clojure.set  java.net.URLClassLoader$1.run (:-1)
```

**Comment by oakes** [comment]
You should be able to fix this by adding `(:require 'clojure.set)` to your `ns` declaration, or by typing `(require 'clojure.set)` in your REPL. The "Test" button just runs `lein test`, which doesn't require the clojure.set namespace by default. I'm not familiar enough with midje or Light Table to know why the same issue doesn't happen there; I suppose they bring in that namespace automatically.

**Comment by jarcane** [comment]
Thanks; I figured that would be the simple fix, just seemed odd that it wasn't in the default namespace in Nightcode, esp. since the autocomplete/autodoc window even recommends it (I guess the AC doesn't check what's actually in the name space before recommending something?)

**Comment by oakes** [comment]
I think it's a Leiningen behavior, so it's not something I can control. I'll close for now; let me know if you have other issues.
