### ISSUE TITLE
Bug: Removing elide character with Paredit mode.

### ISSUE THREAD

**Issue by dubiousdavid** [oakes/Nightcode#127]
When paredit mode is enabled, you can’t backspace to delete `#_`.  The hash symbol can’t be deleted.

**Comment by oakes** [comment]
Yeah, I guess the workaround right now is to select it first. It's kind of hard for me to fix because it would require modifications to the library I'm using.

**Comment by oakes** [comment]
On second thought, I could probably tweak [paredit-widget.core](https://github.com/oakes/Nightcode/blob/master/src/clojure/paredit_widget/core.clj) to fix this. I'll look into it when I get the chance.

**Comment by dubiousdavid** [comment]
On a totally unrelated note, I’m teaching some guys I work with Clojure using Nightcode.  Thanks for creating it.

**Comment by oakes** [comment]
Absolutely, that is great to hear!

**Comment by oakes** [comment]
Fixed in 5bf0b8a6b812ae61fea6d17af4b1ac99316e385d.
