### ISSUE TITLE
Feature Request: Clojure Code formatter

### ISSUE THREAD

**Issue by Immortalin** [oakes/Nightcode#129]
A built-in [Clojure code formatter](http://stackoverflow.com/questions/17829584/is-there-an-online-tool-to-auto-indent-and-format-clojure-code-like-there-are-ma) that formats code on save similar to the gofmt tool would be very nice and save a lot of keystrokes indenting and formatting. Thanks!

**Comment by birdspider** [comment]
so basicly 
````
(clojure.pprint/write
 	THE-FORM-OF-INTEREST
 	:dispatch clojure.pprint/code-dispatch)
````
bound to a key, replacing the actual form?

**Comment by birdspider** [comment]
concept: https://gist.github.com/birdspider/97a8a13ac49383a90cc5

but for some reason the pprint replace, results in a "string" 

````
;;; from find - replace
(defn y [] (x))                          
java.lang.String
;;; from pprint-replace-form!
"(defn y [] (x))"      
java.lang.String
````

**Comment by Immortalin** [comment]
See [this](https://github.com/weavejester/cljfmt)
