### ISSUE TITLE
Feature Request: Compatibility with Sublime Text/Textmate themes

### ISSUE THREAD

**Issue by Immortalin** [oakes/Nightcode#130]
Hi, it would be really great if one could use Sublime Text/Textmate themes with Nightcode as it would  greatly expand Nightcode's selection of themes and not be limited to RSyntax themes since those are not as common.

**Comment by salmazov** [comment]
I agree with Immortalin, Sublime themes would be great. In common, Monokai.

**Comment by oakes** [comment]
I don't know of any way to get RSyntaxTextArea to read those themes but PRs are welcome.
