### ISSUE TITLE
Frequent Attempting to call unbound fn: errors : Windows

### ISSUE THREAD

**Issue by mAch17** [oakes/Nightcode#131]
Hi,

I keep getting these errors very frequently on Windows in Run in REPL option (no problem during Build) . They sometimes go away on rebuilding, but other times stay. I can run the absolutely same program on lein, so it is bugfree as such.

**Comment by oakes** [comment]
Please let me know if you notice this issue in the new version of Nightcode; it may no longer be an issue now that the rewrite has occurred.
