### ISSUE TITLE
Feature Request: Exit button or similar

### ISSUE THREAD

**Issue by dumptruckman** [oakes/Nightcode#132]
I'd really like to see some sort of button or menu option to exit Nightcode. I ask for this as I use the program in a crouton integration window on my chrome desktop. If i close the crouton integration window using the X button on the chrome window (rather than a button in the program within that window) then the program doesn't actually close and becomes unreachable. To make matters worse, I cannot reopen the program without force terminating my chroot.

**Comment by birdspider** [comment]
what about `Ctrl-q` ?

**Comment by dumptruckman** [comment]
That does the trick. Thanks.

I still think there ought to be something visible that shows this shortcut.

**Comment by oakes** [comment]
I'll try to think of a place to show the shortcut, but since it corresponds to the system's window close button I can't display a hint over it.
