### ISSUE TITLE
Font Anti-Aliasing

### ISSUE THREAD

**Issue by salmazov** [oakes/Nightcode#133]
Hi!

I think it would be great if program will have anti-aliased fonts. Smooth fonts I mean. Maybe I can set up settings for fonts in NC?

**Comment by birdspider** [comment]
nightcode should have AA-fonts, if not:

I recommend to update to jre8 and trying to fiddle with (https://wiki.archlinux.org/index.php/Java#Better_font_rendering) `awt.useSystemAAFontSettings=on, swing.aatext=true` as startup params

Depending on your System (win,linux,osx) there might be even more settings for `java` and/or the system.

How it looks at my end:

![nightcode-fonts](https://cloud.githubusercontent.com/assets/370960/8181826/a07bfe70-1429-11e5-819d-045ad58eeede.png)

**Comment by salmazov** [comment]
So, NC depends on Java Rendering System. Yes?

So can I find easy steps to improve fonts rendering? Just update to JRE8?

**Comment by birdspider** [comment]
> So, NC depends on Java Rendering System. Yes?

well NC runs on the jvm - its for all intends and purposes a `java` program, so - yes.

> So can I find easy steps to improve fonts rendering? Just update to JRE8?

jre6 in particular and jre7 to some extend have known issues with fonts, if jre8 update is as easy as it should be I would give it a try

**Comment by oakes** [comment]
Yeah I believe JRE 8 should fix these issues; let me know if it doesn't.
