### ISSUE TITLE
when build Android, "Java compiler not found"

### ISSUE THREAD

**Issue by 5alamander** [oakes/Nightcode#135]
When build Android, it throw:
Java compiler not found; Be sure to use java from a JDK
rather than a JRE by modifying PATH or setting JAVA_CMD.

And there is   "D:\Program Files\Java\jdk1.8.0\bin;"   in the Path

I just don't know how to fix it,   (⊙﹏⊙) ？

**Comment by Immortalin** [comment]
Try adding appending D:\Program Files\Java\jdk1.8.0 to the PATH

**Comment by 5alamander** [comment]
@Immortalin Thanks, I'll try

**Comment by senyuyuan** [comment]
me too..
![image](https://cloud.githubusercontent.com/assets/13503770/10536114/17774e7a-741b-11e5-8a77-870aa98f55a4.png)
but , in my PATH
![image](https://cloud.githubusercontent.com/assets/13503770/10536137/443af6b4-741b-11e5-8cd3-2375c6a1005a.png)
in my console：my java version
![image](https://cloud.githubusercontent.com/assets/13503770/10536161/83527f02-741b-11e5-94bf-c65f52970124.png)

Thanks.

**Comment by oakes** [comment]
Now that I've updated to the latest lein-droid, I'm hoping this issue is resolved. Please let me know if otherwise.
