### ISSUE TITLE
Identifier style token applies to incorrect text

### ISSUE THREAD

**Issue by dumptruckman** [oakes/Nightcode#137]
It would seem that the IDENTIFIER style token in dark.xml and light.xml is applying to all text that is not otherwise formatted. This doesn't seem like the way it should be as it makes it impossible to recolor just function names.

**Comment by oakes** [comment]
This would be an issue for [RSyntaxTextArea](https://github.com/bobbylight/RSyntaxTextArea) since it has to do with its template system.
