### ISSUE TITLE
How to access autocomplete?

### ISSUE THREAD

**Issue by helarqjsc** [oakes/Nightcode#138]
Sorry for submitting a simple question like that here. When I edit a .cljs file, I don't see any autocomplete window popups. What do I need to do to access it? Is there a hotkey? I assume that this IDE has an autocomplete feature, because it's mentioned in #128 and the file  Nightcode/src/clojure/nightcode/completions.clj seems to be doing exactly that. I just can't figure out how to make it show.
Having some kind of Readme/Getting Started tutorial would be really nice.

**Comment by oakes** [comment]
Try clicking the Doc button and completions should be enabled. The name isn't that clear but I needed to save space :)

**Comment by helarqjsc** [comment]
Thanks! It works with clojure.core functions like map, but when I work with Om it doesn't. What could be the reason? [Om does have doc strings](https://github.com/omcljs/om/blob/master/src/om/core.cljs#L1224), so it seems like it should be working

**Comment by oakes** [comment]
Yeah it doesn't do completions for third party libraries at the moment.

**Comment by jconti** [comment]
I wonder if it is reasonable design to replace nightcode.completions/*namespaces* with an optional list of namespaces in the project.clj file?  It would solve the problem of per-project customization.

Another option might be to rescan saved files with https://github.com/clojure/tools.namespace, so all used namespaces would autocomplete.

Any thoughts on these or other related ideas?  Autocomplete on a whole project seems like the kind of feature that would be friendly to new Clojure programmers (coming from more traditional IDEs).

**Comment by peter-kehl** [comment]
Hi Zach,

Is autocomplete present in 2.6.0? I can't see any "Doc" button. Help please.
