### ISSUE TITLE
Reload'ing a file with a compilation error doesn't emit any message

### ISSUE THREAD

**Issue by Grahack** [oakes/Nightcode#140]
First, thanks for NC. It's an easy way to make me and my students work with Clojure.

On Windows,

* Create a console project.
* Then `Run with REPL`.
* Execute `(-main)` in the REPL, so far so good.
* Remove a parenthesis to make the file not pass the compilation.
* `Save` and `Reload`. Everything seems OK [1].
* Executing `(-main)` still works!
* To see the compilation error, one has to `Stop`  then `Run with REPL` again.

Is there any reason for this?

[1]: As when you just change `"Hello, World!"` to `"Hello, Cowabunga"`. `Save` and `Reload` works as expected in this case.

**Comment by Grahack** [comment]
I noticed that some `java.exe` processes prevent us to remove directories, even if `Remove`d from NightCode. My guess is that it's related to this issue.

**Comment by oakes** [comment]
I'll take a look at this soon, sorry for the delay. I'll need to make a Windows VM in order to test it.

**Comment by oakes** [comment]
This should be fixed now.

**Comment by Grahack** [comment]
Indeed. Big thx.
