### ISSUE TITLE
question : Does anyone know how to add nightcode to a docker image

### ISSUE THREAD

**Issue by rwobben** [oakes/Nightcode#142]
Hello, 

I work with clojure on a Docker image. 
Does anyone succeed in making Nightcode work on a docker image. 

Roelof

**Comment by oakes** [comment]
Sorry, I am not familiar with Docker, but I'm sure you could make it work the same way you would with any JAR file. It might help to ask on the [subreddit](https://www.reddit.com/r/Nightcode).
