### ISSUE TITLE
Use NightCode for coding in a DSL

### ISSUE THREAD

**Issue by Grahack** [oakes/Nightcode#143]
Hi,
I'm writing a simple language in French, currently embedded in another Lisp than Clojure:
http://microalg.info
I see that you embed plugins in NightCode to build for some different targets.
Would it be possible to configure/add a plugin to NightCode so as to make it an IDE for another language?
It should be as simple as preloading a `.clj` file, but I don't know where to begin.
Thanks.

**Comment by oakes** [comment]
I am not planning on supporting other languages at this time. If you're just looking to add syntax highlighting, you can look in `utils.clj` which is where it associates file extensions with highlighting rules.

**Comment by Grahack** [comment]
Not sure I was clear enough.  
My «other language» is not more than a bunch of function definitions in a `.clj` file. But maybe I should make it a regular module to import. I just wanted to avoid

      (:require [microalg :refer :all])

Syntax highlighting is a good addition indeed but not mandatory at this time. When I have time I may work on this and fork NightCode if there is no other mean. Do you plan to add an option to have rainbow parentheses?

**Comment by oakes** [comment]
I would like rainbow parens but I'm not sure how to implement that in RSyntaxTextArea.

**Comment by Grahack** [comment]
I wrote a lexer for syntax highlighting my language in Lua for using in [SciTE](http://www.scintilla.org/SciTE.html). See [this file from line 116](https://github.com/Microalg/microalg/blob/master/editeurs/scite/microalg.lua#L116).
Now it's "just" a matter of adapting the algorithm for [RSTA's mechanism](https://github.com/bobbylight/RSyntaxTextArea/wiki/Adding%20Syntax%20Highlighting%20for%20a%20new%20Language)!
One problem though: it may not be possible to make it a simple addition to the current highlighter of Clojure code. We may have to reimplement it.
