### ISSUE TITLE
Is master stable enough for use in a workshop?

### ISSUE THREAD

**Issue by plexus** [oakes/Nightcode#145]
First of all, thank you for NightCode! We used it successfully for the first ClojureBridge Berlin workshop last July, and will use it again for our second workshop this weekend. The ease of installation and the minimal, beginner friendly interface are simply perfect for our use.

Would you recommend sticking to the latest stable release (0.4.7), or could we just as well build an uberjar from master? Is there anything in master that would be helpful, vs are there things that might not be 100% stable?

**Comment by oakes** [comment]
That's great to hear you found it useful for your workshop. The latest
stable release is 1.0.0 which I released a few days ago.

**Comment by plexus** [comment]
:100:
