### ISSUE TITLE
Nightcode in the classroom, only one itch so far: Ctrl-Shift-X

### ISSUE THREAD

**Issue by fredokun** [oakes/Nightcode#147]
I have just tested Nightcode for the first labwork of a third-year undergraduate course about
"declarative programming" based on Clojure.  It is really IMHO the perfect
environment for beginners, definitely better than crossing the emacs barrier (I will introduce
 them to Cider in a further labwork, and then they will choose their own favorite environment).

There's only one recurring complaint so far from the students (and their teacher) : 

> the  `Ctrl-Shift-X` shortcut for the very useful `Eval` command.

 I would agree that there is a problem with this short cut if used frequently: the keys are very close to each other (both on QWERTY and AZERTY keyboards) and it's not good for the hand (think *Carpal tunnel syndrome*).

I think `Run with REPL` is meant to be used less often  so I would suggest a two-keys short cut such as  `Ctrl-E` for `Eval` and maybe `Ctrl-Shift-R`   for the `REPL` ?

An alternative: `Ctrl-Enter` ?

**Comment by birdspider** [comment]
this should be possible by using a modified version of [nightcode.edn](https://github.com/oakes/Nightcode/blob/master/nightcode.edn) and according to this [reddit-post](https://www.reddit.com/r/Nightcode/comments/2d5yvg/new_release_of_nightcode_0310_read_settings_from/) putting it into `~/nightcode.edn` or `~/.config/nightcode.edn`

**Comment by oakes** [comment]
Thanks for the feedback, I just changed the code so `Run with REPL` and `Eval` are swapped. As @birdspider mentioned, you can use nightcode.edn to change the behavior without building a new version of Nightcode. I already changed it to swap those two, so you should be able to just download the file and place it in your home directory.

**Comment by fredokun** [comment]
Thank you @oakes and @birdspider.  I have just tested and the new `Eval` shortcut just rocks ! I think the students will enjoy that.  I will also show them how to play with the EDN e.g. to change the theme ... They will enjoy that too (especially when I'll explain this is clojure data ;-) !
