### ISSUE TITLE
Horizontal REPL / Vertical Split

### ISSUE THREAD

**Issue by codxse** [oakes/Nightcode#148]
Hello Zach, I bought Nightcode from AppStore, how do I split the REPL side by side with the editor vertically?? 

Thanks

**Comment by oakes** [comment]
You can edit [nightcode.edn](https://raw.githubusercontent.com/oakes/Nightcode/master/nightcode.edn) and save it to `~/Library/Containers/info.oakleaf.nightcode/Data/nightcode.edn`. That's the special home directory for the MAS version of Nightcode.

**Comment by oakes** [comment]
Let me know if that doesn't work...I haven't tried it =)

**Comment by codxse** [comment]
Hi Zach, thanks. I have tried it, it doesn't work. :((

**Comment by oakes** [comment]
OK I'll take a look soon.

**Comment by oakes** [comment]
Sorry for the delay. I just tested it and it does indeed work. Please make sure that you put the file in the right place, and that you edited it so it says `:panel :horizontal`.

**Comment by codxse** [comment]
Thanks, it does work. :+1:
