### ISSUE TITLE
Auto-indent on `enter` key

### ISSUE THREAD

**Issue by fredokun** [oakes/Nightcode#149]
Another suggestion from a few of my students: auto-indent after hitting the `enter` key. 
This would "save" one `tab` keypress, but most of all I would not have to tell them to indent correctly afterwise (especially since I told them indentation is "almost" automatic thanks to Clojure's simplistic syntax... Anyways, after two weeks of class I can say that it is a great pleasure to teach with nightcode.

**Comment by oakes** [comment]
Thanks very much for the feedback again. Can you explain a scenario where it isn't auto-indenting? It should be doing that right now. For example, if you type `(defn hello []` and then hit enter, it should indent the next line by two spaces.

**Comment by fredokun** [comment]
I'm sorry @oakes for the late reply, I can only test with the student on mondays...

I can confirm that  if I type `(defn hello []<ENTER>(println "hello"))`  we obtain:

```clojure
(defn hello []
(println "hello"))
```
Without indentation (which thanksfully gets "repaired" by a single <tab> press).

One of the student downloaded nightcode 1.0.0 from the website and is experiencing
the same issue.

FYI :

```
$ lein -v
Leiningen 2.5.3 on Java 1.7.0_07 Java HotSpot(TM) 64-Bit Server VM
$ uname -a
Linux ssh 2.6.32-5-amd64 #1 SMP Sun May 6 04:00:17 UTC 2012 x86_64 GNU/Linux
```

**Comment by oakes** [comment]
I can't reproduce this. On Ubuntu 14.04, it indents two spaces with or without paredit enabled.

**Comment by oakes** [comment]
Please try the latest snapshot build below. It uses a new auto-indentation system:

https://github.com/oakes/Nightcode/releases/download/1.1.0-SNAPSHOT/nightcode-1.1.0-SNAPSHOT-standalone.jar
