### ISSUE TITLE
no feedback for incomplete and/or incorrect expressions

### ISSUE THREAD

**Issue by fredokun** [oakes/Nightcode#150]
If I select an incomplete expression (or I put the cursor at the end), such as `(+ 2 3`   and I click on `eval` then nothing happens, there is no feedback. What is the most problematic for learners is when the problem occurs in a context such as the following

```clojure
(defn test [a b]
  (let [c (+ a b)) ;; <-- typical student mistake !
     (* c a b)))
```

They often make such errors and they don't what happens when there 
is no feedback when `eval`uating

In the repl I of course get a bunch `Unmatched delimiter: )` exceptions...

**Comment by oakes** [comment]
I plan on addressing this next. I believe it's the same as #140.

**Comment by oakes** [comment]
This should be fixed now.
