### ISSUE TITLE
cannot compile and run nightcode, master and release  1.0.1

### ISSUE THREAD

**Issue by fredokun** [oakes/Nightcode#151]
Hi, I cannot compile and run nightcode on my computer

  - cloning the master branch of repository  `lein compile`   (or `lein run`) hang ...

```
> lein compile
Compiling 4 source files to <...removed...>/Nightcode/target/classes
Compiling clojure.main
Compiling nightcode.core
Compiling nightcode.lein
```

I can see that a `java` process is ongoing but `top` says `%CPU` is 0,0

  - when trying `java -jar nightcode-1.0.1-standalone.jar`  the  "NC" banner appears but then the program aborts (without any message, no exception, nothing) and the shell simply returns.

I am trying these on a PC running Debian 8:

```
> uname -a
Linux tatooine 4.3.0-1-amd64 #1 SMP Debian 4.3.3-7 (2016-01-19) x86_64 GNU/Linux
```

```
> lein -version
Leiningen 2.6.1 on Java 1.7.0_91 OpenJDK 64-Bit Server VM
```

**Comment by oakes** [comment]
I also can't reproduce this =( I'm using Leiningen 2.6.1 on Ubuntu 14.04 and have no problems with `lein run`. The splash screen appears and then the window appears shortly afterwards. Perhaps there's something unique about Debian 8 that is causing this problem.

**Comment by oakes** [comment]
Let me know if this is still an issue with the latest release and I'll reopen.
