### ISSUE TITLE
Truncated UI text

### ISSUE THREAD

**Issue by AvramRobert** [oakes/Nightcode#154]
Well hello!
It is to my great displeasure to have to briefly resurrect issue #103, as I have encountered the same UI problem mentioned there. 

After hysterically poking at this problem, I came to the conclusion that, for me at least, this only occurs under very high screen resolutions. 2880 x 1620 to be more exact.
The very moment I change it to a lower one, the problem goes away.
 
I do not know if the following has been mentioned elsewhere, but I've opened this issue not to solely report the problem, but rather to also provide a solution that doesn't implicate tweaking the global OS font scaling factor (as mentioned in #103). Which I tried.. and it did not go so well.

The solution is to simply increase the button width factor in ui.clj. (70 was the magic number for me)

```clojure
(defn adjust-button!
  "Adjusts the given button to fit its contents."
  [^JComponent btn]
  (let [width (-> (.getFontMetrics btn (.getFont btn))
                  (.getStringBounds (.getText btn) (.getGraphics btn))
                  .getWidth
                  (+ 30)) ;;increase until satisfied
        height (-> btn .getPreferredSize .getHeight)]
    (doto btn
      (.setPreferredSize (Dimension. width height)))))
```

So clone nightcode, adjust the factor and then build a new and pimped out jar file. That should do it.

I believe this issue can also be immediately closed.
I apologize for the mild disturbance.

(As a small tangent, I edited and compiled nightcode, with nightcode. It felt cool and rather inceptiony. Just wanted to mention it)

**Comment by oakes** [comment]
Thanks for mentioning this, I will look for a way to make that code resolution-agnostic so we can do away with the magic number entirely. I'll write again if I find something, so you can test it on your hi-res display.

**Comment by oakes** [comment]
I ended up removing that function altogether and using the default button widths instead, so I believe that will fix this issue.

**Comment by AvramRobert** [comment]
It did. Thank you!
