### ISSUE TITLE
MS Windows "Run with REPL" window not usable

### ISSUE THREAD

**Issue by jconti** [oakes/Nightcode#156]
Apologies if the title is overly vague.  Please update it if something better occurs to you.  The system is Windows 10.  The code is tip of trunk b07d26fd211a49df7adde797dd7d565fe0be5261. The symptoms are:
* Run a project with "Run with REPL"
* At REPL prompt type \( and RET.  Neither paren is visible on the screen, but the empty list works.
* Then at repl try to type "(inc 1)".  Each character seems to be its own line of input.

> uru.core=> 
>            
>            
>              
>            
>            
>            
>            
>              
>            
>            
>            
>            
> 
>              
>            
>            
>            
>            
>              
> 1
>            
>            
>            
>            
>              
>            
>  
>            
>            
>            
>              
>            
>            
> c
> i
>            
>            
>              
>            
>            ()n
> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 1
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> CompilerException java.lang.RuntimeException: Unable to resolve symbol: c in this context, compiling:(C:\Users\jconti\AppData\Local\Temp\form-init2823552686370310318.clj:1:1269) 
> uru.core=> 
> uru.core=> 
> CompilerException java.lang.RuntimeException: Unable to resolve symbol: i in this context, compiling:(C:\Users\jconti\AppData\Local\Temp\form-init2823552686370310318.clj:1:1269) 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> 
> uru.core=> ()
> 
> CompilerException java.lang.RuntimeException: Unable to resolve symbol: n in this context, compiling:(C:\Users\jconti\AppData\Local\Temp\form-init2823552686370310318.clj:1:1269) 
> uru.core=> 
> uru.core=>

**Comment by oakes** [comment]
Yep I was informed of this issue recently. Apologies for introducing the bug -- I'm working on tracking it down at the moment.

**Comment by oakes** [comment]
This should now be fixed in master. If you are able to, I would love to hear if it works for you. I tested it in a Windows 10 VM.

**Comment by jcrumpton** [comment]
I just tried the new code from master and "Run with REPL" now works for me (in Windows 7). Thank you!

**Comment by jconti** [comment]
Windows 10 looks good on real hardware too.  Thank you!
