### ISSUE TITLE
Parinfer mangles pasted code

### ISSUE THREAD

**Issue by jcrumpton** [oakes/Nightcode#157]
Pasting code into Nightcode mangles the grouping symbols. For example pasting (from http://www.braveclojure.com/do-things/)

(if true
  "By Zeus's hammer!"
  "By Aquaman's trident!")

results in 

(if true)
  "By Zeus's hammer!"
  "By Aquaman's trident!"

This is true for both the REPL pane and the editor. Is it possible to disable parinfer, either all together or at least during pasting code?

**Comment by oakes** [comment]
This issue should now be fixed. Please let me know if you still see paste issues with the latest commit.

**Comment by jcrumpton** [comment]
It now works great in the editor pane. The pane in the lower left (I called it the REPL pane but maybe it is called the pad?) still mangles the parentheses.

**Comment by oakes** [comment]
Are you sure? I tried pasting your if statement into the REPL pane and it looks like this:

![image](https://cloud.githubusercontent.com/assets/216147/14535459/f5ca5588-023b-11e6-9baa-cdfd74e1ac03.png)

**Comment by oakes** [comment]
Ah I see, thank you for testing it out. I'll go ahead with a new release.
