### ISSUE TITLE
List of keyboard shortcuts

### ISSUE THREAD

**Issue by JoePython1** [oakes/Nightcode#159]
What is the keyboard shortcut to evaluate an expression?
Is there a list of keyboard shortcuts available?

**Comment by oakes** [comment]
Yeah you can see the list in the `:keys` map in [nightcode.edn](https://github.com/oakes/Nightcode/blob/master/nightcode.edn). You can eval a selection with ctrl + e (or command + e on OS X), but you need the REPL running first by clicking Run with REPL.

**Comment by minghu6** [comment]
the url of nightcode is missing ...
