### ISSUE TITLE
Alt+Tab on Windows indents code in the editor

### ISSUE THREAD

**Issue by nikonyrh** [oakes/Nightcode#160]
I'm just learning Clojure and thus alt-tabbing a lot between the editor and browser (on Windows 7).
It took me a while to realize that this action is not ignored by Nightcode 1.3.0 but instead it modifies the source code. Typically it "merges" the expression with the previous one, which is quite frustrating.

Thanks for the great work on this project, I just wish I didn't face this issue once every minute.

**Comment by oakes** [comment]
I just noticed this yesterday after installing windows 10. I'll definitely look into it.

**Comment by medvedutka** [comment]
Same issue under linux (opensuse tumbleweed).

**Comment by oakes** [comment]
Still an issue with the new version of Nightcode. I'll try to look into this soon.

**Comment by oakes** [comment]
Oops, didn't mean to close.

**Comment by oakes** [comment]
Fixed in 2.0.3.
