### ISSUE TITLE
Paren-matching too aggressive sometimes

### ISSUE THREAD

**Issue by adiron** [oakes/Nightcode#161]
Sometimes,  when editing code I have encountered issues with the paren-matching being far too aggressive. This happens especially with comments. When I start a comment while having trailing parens those then become comments and then don't get matched so it assumes it needs to close expressions again and the comment ends up being outside the desired block. 😿 

I'm adding a screencap that shows an example.

![Example of what I mean](http://i.imgur.com/Edkrsmf.gif)

**Comment by oakes** [comment]
You can actually keep typing after hitting enter after the comment, and it will move the paren to the right spot. It's trying to prevent a broken AST even temporarily. Please try that out and let me know if it works for you.

**Comment by adiron** [comment]
Not sure what you mean. When I hit enter after a comment I get tabbed out and have to tab back in. This does the trick, but it's a bit annoying.

Also note how this doesn't happen with strings.

![Another attempt](http://i.imgur.com/10oIoBx.gif)

**Comment by oakes** [comment]
Yep that screenshot is what I was referring to. Is the main issue the fact that you lose your indent level? I can definitely see why that would be annoying. I will try to figure out a workaround for that. The general paren matching behavior is inherent in parinfer, though.

**Comment by adiron** [comment]
I think it's either about losing indent level (I wouldn't have cared so much if that had been the case or maybe handle it like quotes. I'm not sure which would be better although I'm leaning towards quotes.

**Comment by oakes** [comment]
Closing this because the parinfer behavior is pretty set in stone at this point.
