### ISSUE TITLE
nightcode-2.0.0-RC1 - Windows, paredit toggle missing

### ISSUE THREAD

**Issue by Techdread** [oakes/Nightcode#163]
Can't re-position square brackets and can not seem to locate the paredit options to turn it off.
I am sure it was at the bottom right in a previous build.

Great Editor Paul.

**Comment by oakes** [comment]
There was never a paredit toggle in 2.0. I can consider other editing modes
in the future but for now it's just parinfer.

**Comment by Techdread** [comment]
Ok. After playing around with it, I have noticed that if you tab it will auto format for you not obvious for newbies to Clojure like me.

**Comment by oakes** [comment]
I'll look into better ways of documenting that. Thanks!
