### ISSUE TITLE
Switch, theme to Light, restart REPL, get dark REPL

### ISSUE THREAD

**Issue by daveloyall** [oakes/Nightcode#164]
Switch, theme to Light, restart REPL, get dark REPL

**Comment by oakes** [comment]
Hmm I wasn't able to reproduce this. Do you mean the REPL in the home page?

**Comment by daveloyall** [comment]
Yes, the REPL in the home page.

**Comment by oakes** [comment]
I can't reproduce this on Windows 10 or Mac. If you can, please provide a screenshot of this so I can verify we are looking for the same thing. Thank you.

**Comment by daveloyall** [comment]
This isn't a high priority to me, and in fact I haven't touched Nightcode recently, but here are the steps to reproduce, in case this will help you make a polished piece of software. :) 

1. Visit https://github.com/oakes/Nightcode
1. Click Releases
1. Click 2.0.1 (jar)
1. Let it download, tell your computer to execute the jar.  My workspace from 2.0.0 is "just there", nice.
1. Switch to "Home".
1. Switch to "Light Theme".
1. Click "Restart REPL" on top right.
1. REPL is dark.

![capture](https://cloud.githubusercontent.com/assets/1524866/16997928/26ddaf02-4e7d-11e6-88bf-0e31177dbf54.PNG)

**Comment by oakes** [comment]
@daveloyall I thought you meant restart the whole IDE. You are right that this is a bug. Thanks! I'm re-opening this issue.

**Comment by oakes** [comment]
Fixed in 1d34c42b7ac07ac01d799475ff6c14b2be02bb40

**Comment by daveloyall** [comment]
I don't work in clojure, generally speaking, so I'm unfamiliar with Boot, so I can't build this and confirm the fix.  But I'll close anyway because you seem pretty sure!

**Comment by oakes** [comment]
No problem! The fix is now out in version 2.0.2. I appreciate the help.
