### ISSUE TITLE
Can't use arrow keys in REPL to get to previous entries

### ISSUE THREAD

**Issue by SCdF** [oakes/Nightcode#165]
I'm not sure if there is another shortcut for this, but I should be able to navigate to previous entries in the REPL. The standard way (ie bash / lein repl / node / et al) would be the up arrow key. For me (OSX / Nightcode 2.0) that just pops the cursor up for a second before it drops back down.

**Comment by oakes** [comment]
Yep this is an issue, I'll work on this very soon.
