### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Maffblaster** [oakes/Nightcode#166]
Hi Zach,

While you may state the code is in the public domain, that doesn't mean the code actually is in the public domain. You might want to consider something like The [Unlicense](http://unlicense.org/), which speaks the legalize necessary to get the code as close to the public domain as possible. Just a thought!

Kind regards,
-Maffblaster

**Comment by oakes** [comment]
I do indeed use the unlicense, it's in the root of the repo :)

**Comment by Maffblaster** [comment]
Oops! Sorry about that! I missed it from a brief scan of the README.md file. Perhaps you can mention it under https://github.com/oakes/Nightcode#licensing

Thanks for the editor!
