### ISSUE TITLE
Syntax highlight does not comprehed the character \;

### ISSUE THREAD

**Issue by nikonyrh** [oakes/Nightcode#167]
A very minor issue I encountered this when fiddling with HTML escapes such as `&amp;`

Here syntax highlight is treating `;` as starting a comment:
`(= \; (last "the &amp;")))`

**Comment by oakes** [comment]
Can you please post a screenshot? I pasted your code in 2.0 and it looks like this for me:

![image](https://cloud.githubusercontent.com/assets/216147/16820288/4f881ffa-491e-11e6-8419-f83c453ffa0e.png)

**Comment by nikonyrh** [comment]
![nightcode_132](https://cloud.githubusercontent.com/assets/1690501/16820411/9333cc50-4959-11e6-9b1a-738bd3430992.png)

2.0? Great, sorry I was still running 1.3.2.

**Comment by oakes** [comment]
Ah yeah, I just released 2.0 today :)
