### ISSUE TITLE
Error Opening Jar in Ubuntu 16.04

### ISSUE THREAD

**Issue by paullucas** [oakes/Nightcode#168]
`java -jar Nightcode-2.0.0.jar `
`Error: Could not find or load main class net.sekao.nightcode.core`

**Comment by sentenzo** [comment]
the same error
  `$ java -version`
  `    openjdk version "1.8.0_91"`
  `    OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~14.04-b14)`
  `    OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)`

**Comment by oakes** [comment]
Currently you need the oracle version of java to run Java FX. However I could create Linux-specific installers (deb and rpm packages) that bundle the JRE and that would resolve this issue. I will look into that.

**Comment by rosenk** [comment]
this worked for me:
sudo apt install openjfx

**Comment by paullucas** [comment]
@rosenk's solution works! I ended up writing a bash script to automate acquiring the jar file, installing openjfx, and launching the jar file (by running 'nightcode' in terminal). [https://github.com/paullucas/nightcode-bashscript](https://github.com/paullucas/nightcode-bashscript)

**Comment by sentenzo** [comment]
@paullucas, unfortunately, there's no `openjfx` package in Ubuntu 14.04 and in my Mint 17 (wich is based on Ubuntu 14.04). So in fact for me this is not a solution.
It looks to be a common situation for `openjfx` to be absent in some distros. Common enough to have a [github repository](https://github.com/hgomez/obuildfactory/wiki/How-to-build-and-package-OpenJDK-8-with-OpenJFX-on-Linux), devoted to this issue.

**Comment by oakes** [comment]
I'll reopen this until I get native deb/rpm installers up on the website.

**Comment by oakes** [comment]
There are now deb and rpm installers on the website. Please let me know if they don't work. They should install Nightcode into `/opt/Nightcode`.

**Comment by allentiak** [comment]
This problem is still present in Nightcode 2.3.2.
Although the DEB package works (Debian testing/"Stretch"), I cannot execute the .jar unless I install OpenJavaFX...
`sudo apt install openjfx`
What about simply adding the dependency to the packages?

**Comment by oakes** [comment]
@allentiak I'm confused about what you are asking or suggesting. The library is required to run the jar, not the packages.

**Comment by aaronchall** [comment]
@oakes I could not launch the latest jar without rosenk's solution - latest .deb didn't work in 16.04 (at least after "installing (sudo dpkg -i Nightcode-2.3.3.deb)" I still couldn't find the executable)...

**Comment by oakes** [comment]
@aaronchall Did you check `/opt/Nightcode`?

**Comment by crantok** [comment]
In case this is useful information for future releases...

I tried following the ClojureBridge instructions to install Nightcode 2.3.3 on my computer running Ubuntu Server 16.04 LTS.  I downloaded the jar file, ran `java -jar Nightcode-2.3.3.jar` and saw this response:
```
Error: Could not find or load main class nightcode.core
```
I found the current issue thread by searching for that error message and decided to try installing via deb file instead. I ran `sudo dpkg -i Nightcode-2.3.3.deb` and got this response:
```
Selecting previously unselected package nightcode.
(Reading database ... 167855 files and directories currently installed.)
Preparing to unpack Downloads/Nightcode-2.3.3.deb ...
Unpacking nightcode (1.0) ...
Setting up nightcode (1.0) ...
Adding shortcut to the menu
xdg-desktop-menu: No writable system menu directory found.
dpkg: error processing package nightcode (--install):
 subprocess installed post-installation script returned error exit status 3
Errors were encountered while processing:
 nightcode
```
I followed up with `sudo apt-get install -f` in case there was a dependency problem and got:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up nightcode (1.0) ...
Adding shortcut to the menu
xdg-desktop-menu: No writable system menu directory found.
dpkg: error processing package nightcode (--configure):
 subprocess installed post-installation script returned error exit status 3
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Nightcode is not in my PATH but, having read the current issue thread, I knew to check in my /opt/ directory, which contained directories `atom` and `Nightcode`. I was able to run Nightcode by using the full path to the executable.

**Comment by crantok** [comment]
Further to that error about menus after installing the deb file:

I now see that error every time I install anything with apt-get. As a solution I tried to purge Nightcode, but purging failed with the same error:
```
$ sudo apt-get purge nightcode
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED
  nightcode*
0 to upgrade, 0 to newly install, 1 to remove and 46 not to upgrade.
1 not fully installed or removed.
After this operation, 220 MB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 171749 files and directories currently installed.)
Removing nightcode (1.0) ...
Removing shortcut
xdg-desktop-menu: No writable system menu directory found.
dpkg: error processing package nightcode (--purge):
 subprocess installed pre-removal script returned error exit status 3
Errors were encountered while processing:
 nightcode
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
