### ISSUE TITLE
Instarepl incorrectly reports error in macro

### ISSUE THREAD

**Issue by optevo** [oakes/Nightcode#169]
With the following macro:
(defmacro condf
  [& forms]
  `(condp #(%1 %2) ~@forms))

The instarepl says:
java.lang.RuntimeException: Unable to resolve symbol: forms in this context, compiling:(NO_SOURCE_PATH:0:0)

**Comment by oakes** [comment]
I think this is a general issue with the editor not actually parsing the macro correctly. I'm using tools.reader which currently seems to have issues with the shorthand lambda syntax. As a workaround, I was able to get the following to work, but I'll certainly consider this a bug and see if I can find a fix.

```clojure
(defmacro condf [& forms]
  `(condp (fn [] (%1 %2)) ~@forms))
```

**Comment by oakes** [comment]
This should now be fixed. Please let me know if you still experience it.

**Comment by optevo** [comment]
Looks good! Thanks!
