### ISSUE TITLE
boot run produces Error: Could not find or load class clojure.main 

### ISSUE THREAD

**Issue by paulrd** [oakes/Nightcode#170]
I'm using ubuntu 16.04. openjfx installed. Uberjar (boot build) works fine though (repl loads).

**Comment by oakes** [comment]
See #168

**Comment by paulrd** [comment]
#168 is not an issue for me I only get the problem when I do:

```sh
boot run
```

java -jar target/project.jar works fine.

**Comment by oakes** [comment]
Ah yes, running processes only works from the jar file, not when running boot run. Since this only affects development I'm not looking to solve the issue right now. It is caused by the way I am launching processes from inside the jar.
