### ISSUE TITLE
InstaREPL doesn't work with third-party libraries

### ISSUE THREAD

**Issue by Severed-Infinity** [oakes/Nightcode#171]
No matter the library I am using for some reason I get the error mention in the title where 'library_name_here' is a stand in for any library, searching online revealed little to no results despite the error popping up in so many links. The best result I could find was a compatibility issue between leiningen version and java version but that does not appear to be the case.
 
I'd also like to point out I use this project in Cursive with no issues. 

I created a new project just incase it might have been an issue with the project I opened but no I got the same results. Below you find some images with the issues.

OS X El Capitan
Version 10.11.5

Leiningen 2.6.1 on Java 1.8.0_92 Java HotSpot(TM) 64-Bit Server VM

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Since macs use the cmd key for screen shots you might find some of the keyboard shortcuts for nightcode pop up in the screen shots and cover some tiny areas.

InstraRepl on projects core.clj file
<img width="582" alt="screen shot 2016-07-14 at 21 35 52" src="https://cloud.githubusercontent.com/assets/4560707/16854930/058eec7e-4a0b-11e6-9856-c2799baab1b9.png">

project directory structure
<img width="244" alt="screen shot 2016-07-14 at 21 36 08" src="https://cloud.githubusercontent.com/assets/4560707/16854937/091b88a2-4a0b-11e6-940c-f8e868ecf755.png">

project.clj file
<img width="501" alt="screen shot 2016-07-14 at 21 36 16" src="https://cloud.githubusercontent.com/assets/4560707/16854940/0af40ae6-4a0b-11e6-9036-199d952438f0.png">

**Comment by oakes** [comment]
The instarepl unfortunately doesn't work with third party libraries right
now. I plan on fixing that in an upcoming release. I'll keep this issue
open until out it's fixed.

**Comment by Severed-Infinity** [comment]
Ah okay cool, I thought it might have been doing I was doing wrong. That's good to know, I can't wait!

**Comment by hellonico** [comment]
any news ? that would help making people switch from L**tbl.

**Comment by oakes** [comment]
Yep this is next on my list of things to work on. It will enable several other important features as well so it's pretty important.

**Comment by oakes** [comment]
Just to give you an update, this is turning out to be quite difficult to achieve due to nightcode's design. I do, however, have another project I'm working on that complements nightcode and provides a more powerful instaREPL. I'm going to be releasing it soon so i'll leave a message here when that happens.

**Comment by Severed-Infinity** [comment]
Can't wait to have it ready for action!

**Comment by oakes** [comment]
I just released the project I mentioned:

https://github.com/oakes/Nightlight

I will close this issue, because I don't think I can get Nightcode to understand dependencies the way Cider and Cursive do.
