### ISSUE TITLE
Cannot select/copy text in REPL pane

### ISSUE THREAD

**Issue by kreducer** [oakes/Nightcode#174]
I see there's an issue already filed for using arrow keys as history in NC2 (very handy in 1.3.2), but alongside that it'd be good to be able to copy and paste the content from the REPL pane again.

* NC 2.0.0 (from windows installer exe on the site)
* Windows 10
* System JRE 1.8.0_92-b14 (in case that's helpful).

**Comment by oakes** [comment]
Fixed by 02dfd592639d76bbb02c25d3819efc7039fa9ce1
