### ISSUE TITLE
Selection by Form

### ISSUE THREAD

**Issue by NathanSmutz** [oakes/Nightcode#176]
I found the ability to select by form really useful when moving things around or selecting code to evaluate in the REPL.

I remember Nightcode doing this a while back (in the paredit days); I believe using Alt plus an arrow key to select the current form, then the form containing it, etc.

**Comment by oakes** [comment]
Yep this should definitely be doable. Technically this would be a paren-soup feature but I'll leave it here since this project is more publicly facing. I'll look into it soon.

**Comment by oakes** [comment]
Just added this feature in version 2.5.5. I guess it wasn't exactly "soon", but better late than never :) Not entirely sure if it works on windows though.
