### ISSUE TITLE
Shortcuts don't work on Linux

### ISSUE THREAD

**Issue by NathanSmutz** [oakes/Nightcode#177]
Using Linux (Mint 17.3 Cinnamon):

Ctrl + z doesn't undo.
The undo button still works; and Ctrl + Shift + z works for redo.

I've confirmed that this is not a problem in Windows 7 (Running the Nightcode jar)
Ctrl + z is working in other Linux programs; but it still could be something odd with my distro clobbering that key combo.  Are any other *nix users experiencing this?

**Comment by oakes** [comment]
I believe this is a general issue with shortcuts on Linux, so I renamed this issue to reflect that. I'll look into a fix soon.

**Comment by PDAHubbard** [comment]
Seeing same issue under Arch Linux and OpenJDK Runtime Environment (build 1.8.0_92-b14)

**Comment by oakes** [comment]
Fixed in e6b722257f026d5fe621f27160f13688fe492b7b

**Comment by oakes** [comment]
The fix is now available in 2.0.2.
