### ISSUE TITLE
New Project Contents Not Populating

### ISSUE THREAD

**Issue by NathanSmutz** [oakes/Nightcode#178]
Nightcode isn't recognizing any files or folders in a project it created.  Likely this is due to either leading capital letters in the name.

I started a Web App project from the Start menu.
The specified project name was: NC-2_0_0-web

A folder was created with different capitalization in the name:
nc-2_0_0-web 

The originally capitalized project name appears in the side menu; but no files or folders are listed.  Shutting down and restarting Nightcode didn't have an effect.

![image](https://cloud.githubusercontent.com/assets/2293340/16897832/6dbf1ed6-4b73-11e6-9c3d-8ab87cf12eba.png)

![image](https://cloud.githubusercontent.com/assets/2293340/16897867/ef3a27ac-4b74-11e6-9670-98eb06d16f40.png)

**Comment by oakes** [comment]
Fixed in 335721df37a1d12a5478242a4e9290c87da56240
