### ISSUE TITLE
Executing a single expression in the REPL

### ISSUE THREAD

**Issue by hellonico** [oakes/Nightcode#180]
I see how to load/reload the whole namespace in the REPL, but how to load only one expression ?

**Comment by kreducer** [comment]
Is this the functionality that used to be on Ctrl + E in 1.x? Either way, it'd be handy if Ctrl+ E evaluated the currently highlighted rainbowparens form instead of running the current text selection.

**Comment by oakes** [comment]
Yep I think it's a great idea to have it highlight whatever form is currently highlighted, so you don't need to explicitly select it.

**Comment by oakes** [comment]
I added a "Reload Selection" button a few releases ago; forgot to close this issue :)

**Comment by hellonico** [comment]
tested and working great ! thanks.

**Comment by viesti** [comment]
On 2.2.0 seems that "Reload Selection" only prints into console like this: `{:x 0, :text "<selected text"}` and does not evaluate the selection.

**Comment by oakes** [comment]
Uh oh! I'll check it out when I get the chance.

**Comment by viesti** [comment]
[`cross-parinfer.core/mode`](https://github.com/oakes/cross-parinfer/blob/master/src/cross_parinfer/core.cljc#L35) returns a map, which then comes out of `getSelectedText` when called here: https://github.com/oakes/Nightcode/blob/master/src/clj/nightcode/controller.clj#L307.

**Comment by viesti** [comment]
Could have submitted a PR that adds `(:text (cp/mode...)` to https://github.com/oakes/Nightcode/blob/master/src/cljs/nightcode/paren_soup.cljs#L38, but having some difficulty in rebuilding cljs in the project :) Tried out parsing the map in the JVM side, but probably better to fix `get-selected-text`.

**Comment by oakes** [comment]
You need to run `boot build-cljs` and then manually copy paren-soup.js to
resources/public. You can also just submit a PR with the code change and
I'd be happy to compile it when I'm home.

**Comment by viesti** [comment]
Thanks! Managed to test it so here you go :) https://github.com/oakes/Nightcode/pull/215

**Comment by viesti** [comment]
Btw. We'r using Nightcode (which is awesome, nuff said :)) on a coming ClojureBridge saturday this week, but might be a tad bit too close to get this fix in (copy&paste suffices for now) :)

**Comment by oakes** [comment]
I can definitely get it out before then, no worries. Thanks for the fix, I
cringe to think how long this has been broken!

**Comment by viesti** [comment]
Hi! Just checking with a biiiiit of curiosity in me :), but if you have time before saturday for a 2.2.2 release (or think that this might be worth of 2.2.2), you could name this a [ClojureBridge Finland](http://www.clojurebridge.org/events/2017-01-28-helsinki-finland) release :)

**Comment by oakes** [comment]
Yep, I'll cut a release today and will close this issue when that happens so you know it's out.

**Comment by oakes** [comment]
Version 2.2.2 is out! Thanks again.

**Comment by viesti** [comment]
Superb! Thank you :)

**Comment by nikonyrh** [comment]
On Windows 10, Nightcode 2.3.3 the "Reload Selection" button works, and shows the "R" highlight when Ctrl key is pressed but Ctrl+R does not execute the code.

Oh damn nevermind, you need to press Ctrl+Shift+R :D Would it be possible to assign `r` to Reload Selection and `R` to Run? I imagine "Run" is not executed as often as Reload.
