### ISSUE TITLE
Deploy to package managers

### ISSUE THREAD

**Issue by aadrian** [oakes/Nightcode#182]
Hi,

Any plans releasing a brew version too? for easier install/uninstall?

Thank you.

**Comment by oakes** [comment]
I may take on the task of adding the installers to various package managers in the future, but right now my deployment process for new versions is already quite involved. If there was a service that let me upload those packages and took care of deploying them the right way for brew, apt-get, yum, and so on, I'd love it :)

**Comment by birdspider** [comment]
@oakes - no idea if this is any good, but I found this: https://github.com/jordansissel/fpm

**Comment by NathanSmutz** [comment]
In the past, I've been happy to just run the .jar; especially in places where I don't have install permissions or shouldn't leave a footprint.  Do the package manager versions do something special?

**Comment by oakes** [comment]
Closing this because I have settled on providing installers via the website; others are more than welcome to deploy it elsewhere.
