### ISSUE TITLE
Hide 'target' directories from the tree?

### ISSUE THREAD

**Issue by aadrian** [oakes/Nightcode#183]
Hi,

Is there any option to hide the 'target' directories from the tree?

The tree component also seems to have rendering problems with this directory (contains much to many files).

Thank you.

**Comment by oakes** [comment]
You can click the arrow next to the name to collapse the directory.

**Comment by aadrian** [comment]
> You can click the arrow next to the name to collapse the directory.

Hiding directories from the project tree is not the same as collapsing them :).
Most users would expect patterns specified in a .gitignore file to be also ignored/hidden by the IDE too.

**Comment by oakes** [comment]
Does collapsing it not solve your problem? I've never seen an IDE completely hide things specified in `.gitignore`.

**Comment by aadrian** [comment]
> Does collapsing it not solve your problem?

Of course not :). Output directories usually should not clutter the project structure.

**Comment by oakes** [comment]
You said the directory "contains much too many files", so my question was whether collapsing the directory solved that problem. Was that an unreasonable question? Collapsing a directory causes its contents to not display.

**Comment by aadrian** [comment]
> so my question was whether collapsing the directory solved that problem.

No, since the directory is still there, it's accessible, and even if once collapsed it can be opened by accident or by a bug (e.g. restarting the IDE on OSX).
Not having different colors and icons in the tree, makes it harder to distinct those directories, in order for the user to always avoid them.

> Collapsing a directory causes its contents to not display.

It's not displayed, but it's still there, navigable (by intention or by mistake or by bug), causing overhead.

**Comment by oakes** [comment]
It should definitely not re-open after restarting, so if you see that I'd definitely like to look into it more deeply. I just tried it on OS X and was not able to reproduce that behavior.

I would be interested in possibly graying things out if they are `.gitignore`ed but most likely not hiding them completely.
