### ISSUE TITLE
Why not reserve the button `Eval Selection` ?

### ISSUE THREAD

**Issue by minghu6** [oakes/Nightcode#189]
i mean eval automatically switch to the right is fashionable, 
but **eval selection** has max **flexibility**

**Comment by nikonyrh** [comment]
I thought this button had gone missing due to a bug, that is why I'm still using 1.3.2 :/

**Comment by oakes** [comment]
I intend on adding this back soon. It would like to improve how it works, though. In particular, I want it to simply eval whatever form the cursor is inside of, without needing to select the form. This should work well with the form highlighting feature in the editor. It could remain a button in the build pane, or perhaps some kind of contextual button that appears inside the editor when inside a valid form.

**Comment by nikonyrh** [comment]
Great, I hope you'll still be able to also execure a specific piece of code, for example after running `(def xyz (+ 1 2 3))` I'd like to eval `xyz` to confirm it has the value I anticipated. Not sure if "eval whatever form the cursor is inside of" means exactly this.

**Comment by oakes** [comment]
Yep, I could make it use the selection if there is one, but if there is no
selection it will eval the nearest form the cursor is inside of.

**Comment by oakes** [comment]
Just released 2.0.4 with this feature.
