### ISSUE TITLE
Argument literal parsing is broken.

### ISSUE THREAD

**Issue by jggrant** [oakes/Nightcode#191]
Using NightCode 2.0.3, when an argument literal (%n) for an anonymous function (#()) is used, errors appear and syntax highlighting is disabled for that line.

To reproduce:
Type "(map #(+ %1 2) '(1 2 3))" in the home page REPL or source file.

**Comment by oakes** [comment]
Fixed in 52c3ef51fe88e8116d92225472dc6253a930916f

**Comment by oakes** [comment]
Just released the fix in 2.1.0 so I'll close this.
