### ISSUE TITLE
Error: Could not find or load main class net.sekao.nightcode.core

### ISSUE THREAD

**Issue by sotrhRaven** [oakes/Nightcode#192]
Downloaded earlier today got the following error. Tried building got an error dealing with net.sekao.nightcode.core.clj.

Please save me from having to use emacs

**Comment by oakes** [comment]
Did you download the jar version? Also, what version jdk do you have?

**Comment by sotrhRaven** [comment]
Yes Nightcode-2.1.0.jar 
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by oakes** [comment]
Hmm I'm on build 1.8.0_92-b14 so perhaps it doesn't work on later versions. You may have better luck by cloning this repo and running `boot build`. That should result in a file at `target/project.jar`. Perhaps it will work if you build it with the exact same JDK version.

**Comment by sotrhRaven** [comment]
All right, downloaded 1.8.0_92-b14. It started and runs. I couldn't get it to build though.

**Comment by oakes** [comment]
Definitely strange that it doesn't work on the latest JDK. I'll update Java next time I cut a release. Thanks for pointing this out.
