### ISSUE TITLE
InstaREPL reports errors with ' syntax

### ISSUE THREAD

**Issue by jr0cket** [oakes/Nightcode#193]
Using the short form of the quote function reports errors in the InstaREPL

**Example**
Using the short form of quote to a list collection to be just used as data
'(1 2 3 4) 
=> java.lang.ClassCastException: java.lang.Long cannot be cast to clojure.lang.IFn

Using Nightcode version 2.1.1 on Linux (.deb), Java openjdk version "1.8.0_91"

**Comment by oakes** [comment]
Fixed in 24991e999bbf18bcb0a1c48fe8f7e723566db0c5, thanks!

**Comment by oakes** [comment]
Just released 2.1.2 with the fix.

**Comment by jr0cket** [comment]
Thank you, the ' syntax is working correctly now, much appreciated.
