### ISSUE TITLE
Recognize .cljs.hl hoplon files as clojurescript and enable parinfer editing mode.

### ISSUE THREAD

**Issue by smallgreenhorse** [oakes/Nightcode#199]
Would be nice if nightcode could be aware of hoplon .hl file extension
and have parinfer editing mode enabled for hoplon files.
Right now nightcode treats .hl files as just text files.

**Comment by oakes** [comment]
Fixed in c0ecd893318e0b24a7b5312279954bbec2ac44b4, thanks!

**Comment by oakes** [comment]
Just released 2.1.5 which includes this change :)

**Comment by smallgreenhorse** [comment]
Thanks !
