### ISSUE TITLE
Multi-Second Lag on Line Break (maybe minimum hardware requirements?)

### ISSUE THREAD

**Issue by NathanSmutz** [oakes/Nightcode#201]
Is anyone else seeing a lot of lag: unpredictable on typing(can be seconds), multiple seconds before parinfer indents after a line-break.
I'm running the Jar version of 2.1.5
My laptop is a little old: 1.8 GHz (AMD) quad core, 8 gigs ram.  
I'm seeing this on Linux (Mint 17) and Win 7 32-bit. 
Maybe we can hash out some minimum requirements for hitting the Doherty Threshold.

**Comment by oakes** [comment]
I think I fixed this issue in 2.3.0 (I was unnecessarily refreshing when I didn't need to be). Please let me know if you still consider it an issue after trying that version.
