### ISSUE TITLE
bracket match bug when defmacro

### ISSUE THREAD

**Issue by whtoo** [oakes/Nightcode#203]
```
(defmacro foreach [[sym coll] & body]
  `(loop [coll# ~coll]
    (when-let [[~sym & xs#] (seq coll#)]
      ~@body
      (recur xs#))))
```

The second line at this block will raise a bug that Nightcode always attempt to match with ) for `(loop

It stops me to write  the macro correctly.

**Comment by oakes** [comment]
I assume this is no longer a bug because I can open this in Nightcode without issue right now.
