### ISSUE TITLE
Instarepl can't find library

### ISSUE THREAD

**Issue by achikin** [oakes/Nightcode#207]
InstaREPL shows an error when trying to require library.
core.clj
```clojure
(require '[lanterna.screen :as s])
```
project.clj
```clojure
(defproject untitled "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                  [clojure-lanterna "0.9.4"]]    
  :main ^:skip-aot untitled.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```
The following error is shown
```
java.io.FileNotFoundException: Could not locate 
lanterna/screen__init.class or lanterna/screen.clj on classpath.
```
The app builds and runs OK with `lein repl` and `lein run`

**Comment by oakes** [comment]
Yes this is a design issue with Nightcode's instaREPL. It doesn't have access to third party libraries. If you'd like this feature, please consider using Nightlight instead:

https://github.com/oakes/Nightlight

Refer to this issue for a previous discussion:

https://github.com/oakes/Nightcode/issues/171
