### ISSUE TITLE
Reason for removing Quil

### ISSUE THREAD

**Issue by lislis** [oakes/Nightcode#208]
Hey @oakes!
Thank you for your work on Nightcode! We're using it for our ClojureBridge workshop in Berlin.
For the last workshop we used version 2.0.4 which is the last release that includes Quil for the Graphics template which is what our workshop curriculum relies on.  
Unfortunately we also ran into stability problems on a lot of computer with that version. 
So, here is my question: Is there any chance that Quil will make it back into Nightcode in one form or another? 
And out of curiosity (sorry if that was asked somewhere else before): Why did you remove Quil in the first place?

**Comment by oakes** [comment]
Hello, I'm happy to add the template back in. I was not aware that y'all were using it! I'll try to get a new release out by this weekend.

**Comment by lislis** [comment]
Thank you for the quick reply! That would be amazing 🎊

**Comment by oakes** [comment]
I just released 2.1.8 with the graphics template added back.

**Comment by lislis** [comment]
awesome, thank you!
![high five](http://i.giphy.com/OcZp0maz6ALok.gif)
