### ISSUE TITLE
Highlighting with strings and numbers in maps is broken

### ISSUE THREAD

**Issue by Qwerp-Derp** [oakes/Nightcode#209]
What it says on the tin. It highlights a number that's directly after a string (without a space) the same colour as the string itself, despite it being separated.

So, something like

```clojure
{1"-1"2"-2"}
```

becomes

![nightcodebug](https://cloud.githubusercontent.com/assets/14177193/21072017/41ec905a-bf08-11e6-81ac-dfe1e1b09e1a.PNG)

**Comment by oakes** [comment]
Fixed in 2a7d8d99509c29b608ff41dd3b8260e43f36d3ea, thanks!
