### ISSUE TITLE
"No Java runtime present" on MacOSX

### ISSUE THREAD

**Issue by DoctorVin** [oakes/Nightcode#210]
I'm having pretty much the identical issue to #194 with version 2.1.8. I agree this is probably related to the environment on my mac, but I can't figure out what's up.

Lancer:~ drvince$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/zulu8.72.jdk
Lancer:~ drvince$ java -version
openjdk version "1.8.0_72"
OpenJDK Runtime Environment (Zulu 8.13.0.5-macosx) (build 1.8.0_72-b15)
OpenJDK 64-Bit Server VM (Zulu 8.13.0.5-macosx) (build 25.72-b15, mixed mode)
Lancer:~ drvince$ javac -version
javac 1.8.0_72
The one thing I did notice is that /usr/libexec/java_home returns nothing. But I have spent a while fruitlessly trying to get it to notice the JDK I have installed to no avail.

Any suggestions?

**Comment by oakes** [comment]
On my machine, `/usr/libexec/java_home` returns `/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home`. How did you install Java? Did you install the oracle version?

**Comment by DoctorVin** [comment]
I installed OpenJDK from Azul (http://www.azul.com/downloads/zulu/). It's been a while, I think I used the ZIP, so basically I unarchived and moved it into /Library/Java/JavaVirtualMachines.

We could probably address this by having Nightcode honor $JAVA_HOME if it's set. If you don't mind, maybe I'll take a stab at a patch.

**Comment by DoctorVin** [comment]
OK, so in the process of trying to square some other stuff away, I wound up updating my install of OpenJDK using the Zulu DMG installer this time. Unlike the ZIP file install, this actually adds whatever collateral is required to get /usr/libexec/java_home to give me a sensible answer. Now everything works fine. Weird. Thanks for the response.
