### ISSUE TITLE
Why not Nightcode for Linux any more?

### ISSUE THREAD

**Issue by kaluosi** [oakes/Nightcode#212]
I have read your interesting post regarding Nightcoders.net. Maybe it is the way to the future. Meanwhile a I was happy with Nightcode. My surprise was to find that there is a version for Mac, Windows but no a new one for Linux. Why?

**Comment by oakes** [comment]
The embarrassing reason is that my Ubuntu VM, which I built the deb/rpm packages in, stopped working and I was too lazy to create a new one. I'll try to get on that soon.

**Comment by oakes** [comment]
The linux installers are now on the website again.
