### ISSUE TITLE
(read-line) loses the first character when it follows a println

### ISSUE THREAD

**Issue by NathanSmutz** [oakes/Nightcode#217]
Nightcode Version 2.3.0 jar on Windows 7

When (read-line) follows a println statement, it doesn't pick up the first character of your input.   If you backspace to delete while entering input, the first character deletes, but pops back in.  
![image](https://cloud.githubusercontent.com/assets/2293340/23188809/f9886e26-f844-11e6-9f6f-b36668896b09.png)

When running from the REPL, the first character will be gray and the rest will be yellow.   Pressing the up-arrow to repeat previous lines, your input appears without the first character.

Workaround: Replacing (println "Prompt") with (do (print "Prompt") (flush))  fixes the problem.  
Note: print requires you to use (flush) or the prompt wont display.

![image](https://cloud.githubusercontent.com/assets/2293340/23188599/25843c72-f844-11e6-8177-eb8fbb885a7c.png)

Test Code
`(ns error-lab.core
  (:gen-class))

(defn -main []
  (println "Enter Something: ")
  (flush)
  (let [text (read-line)]
    (println "You typed: " text)))`

**Comment by oakes** [comment]
Can you try this in 2.3.1 and let me know if it's still a problem?

**Comment by NathanSmutz** [comment]
Looks like it still happens in 2.3.2 (Linux .deb)

**Comment by oakes** [comment]
This issue is (finally) fixed in master. Thanks!

**Comment by oakes** [comment]
Just released 2.3.6 which fixes this issue.
