### ISSUE TITLE
`(doc ..)` in REPL breaks editing

### ISSUE THREAD

**Issue by jamesnvc** [oakes/Nightcode#218]
After calling the `doc` function in the repl, the cursor seems to jump back to the top of the buffer on every keystroke & typed text is deleted and/or mangled.

Using Nighcode 2.3.0 release on OS X 10.11.6 (but also seeing this behaviour for people on Windows & other versions of OS X/macOS).

Steps to reproduce:
 - Open Nightcode-2.3.0.jar
 - Import a project or create a new one
 - Launch a repl via "Run with REPL" on any file
 - In the repl, type `(doc +)`
 - Try to type more forms, but become unable to

**Comment by oakes** [comment]
Wow that's an ugly bug. I'll check it out.

**Comment by oakes** [comment]
Fixed! And I just released Nightcode 2.3.1 which includes the fix. Thank you for reporting this...it was a mistake I apparently made a long time ago and never noticed.
