### ISSUE TITLE
OpenJDK requires additional JavaFX package

### ISSUE THREAD

**Issue by arichiardi** [oakes/Nightcode#224]
Hello!

I was trying Nightcode locally on my Ubuntu `16.04` and I discovered that OpenJDK does not include JavaFx by default.

I had to launch:

```
sudo apt-get install openjfx
```

Just wanted to report it, and maybe there can be some hint at it in the README or somewhere (if you can point me to it, I can contribute it).

Thanks for the this editor, it is neat :smile:

**Comment by oakes** [comment]
Just added it to the README, thanks! Sorry for the delay...I was driving cross-country when you made this issue :D

**Comment by arichiardi** [comment]
No problem thanks so much!
