### ISSUE TITLE
Stand-alone Jar is fubar

### ISSUE THREAD

**Issue by joinr** [oakes/Nightcode#227]
I've been meaning to report this ever since 2.x came out, with the switch to javafx and webviews.  As it were, you could just grab the nightcode release .jar and run it no problem.  This was (is?) a great feature, since newbs and /or folks in restricted environs could get a decent clojure environment if they only had a JRE installed.  Ever since the switch to 2.x, the editor works great, but run-with-repl using the uberjar launch setup I mentioned has just fundamentally been broken.  Earlier, the repl would just stall out and become non-responsive after evaluating one or two simple forms (like (+ 2 3)).  More recently, I just tried loading a project to revisit NC using 2.3.7, and I get a slew of errors in the repl.

To recreate the problem, I started the jar like a newb would (2x click from Windows 10 /w java 1.8 installed), started a new project called "crashtest", then RunWithRepl.  It compiled the core ns, then got me into the repl.  At which point, I entered (+ 2 3) and pressed enter to eval....

The output from the repl is [here](https://gist.github.com/joinr/0bc8fc0e86f0b191db4c1dcbab6472a4)
Highly interesting: if I run with the distributed .exe nightcode installer, I can't reproduce this problem!  Unfortunately, my use case precludes using the installer, but allows the uberjar....

**Comment by oakes** [comment]
I wasn't able to recreate this. I even fired up a Windows 10 VM and ran the jar the same way, and the REPL behaved normally. It looks like the REPL is trying to evaluate the text that Nightcode is printing to standard output. Weird! I will try to think of what could cause this, but it'll be hard to do a fix until I can recreate the issue.

**Comment by joinr** [comment]
That's befuddling.  I'll try more things to see if I can provide additional forensics on my end.  Note:  the uber-jar problem occurred on windows 7 as well; in that case it manifested as the eventually-dead REPL (probably a similar error wasn't bubbling up to the REPL output....).  Of note:  when I'm encountering issues, I'm not running on a VM (not sure if / why that would effect things; but it's an independent variable...).

**Comment by joinr** [comment]
Here's another datapoint [may not be relevant].  Using 'boot run' I get into NC, then run with repl, NC tells me there's no class "nightcode.core", and in the console I get [this](https://gist.github.com/joinr/a3cb6adfc9a62a48fdf0341a494f9fb4).

**Comment by joinr** [comment]
build.boot appears to succeed, then produces a jar that can't be [launched](https://gist.github.com/joinr/ac74ead252e5513ee3141fcda47b193f)  .

**Comment by joinr** [comment]
So, I created a [commensurate ](https://gist.github.com/joinr/3859bc28b003b1ead7c1cfd60b448db5) lein profile to see if boot was doing something unseemly.  Lein builds the uberjar (and launches) no problem.  Lein repl works fine too.  Except the REPL issue is still there.  As I mess around with it more, it "looks" like the output that should be emitted as a log (i.,e. running with repl, and later on error traces) are being redirected as input to the REPL's input stream.

**Comment by joinr** [comment]
Current guess is that the line 90 of builders.clj, in the event handler for "onEnter", we might be pushing unintentional text to the pipe.  Checking it out...

**Comment by joinr** [comment]
Looks like I was right....
Check out [this commit](https://github.com/joinr/Nightcode/commit/4d923ec2b7a8fee78050bb0748fe84858c4fa061) to see what I did.  I'm thinking about work-arounds for this particular problem (like filtering the text coming from the pipe), but I'm still getting oriented.  Perhaps someone else has ideas?

**Comment by oakes** [comment]
The console works by internally storing [the start position](https://github.com/oakes/paren-soup/blob/master/src/paren_soup/console.cljs#L6), which is how many characters from the beginning the prompt is. The only way the behavior you're experiencing could occur is if that value remained 0 instead of being updated properly.

All REPL output (including lein's preamble) is added to the pane via the [append-text!](https://github.com/oakes/paren-soup/blob/master/src/paren_soup/core.cljs#L340) function, which eventually calls `update-console-start!` with the new start position. I'll have to think about this...there must be some reason it is not updating with the correct start position.

**Comment by joinr** [comment]
After looking through paren-soup, and the associated calls for creating and initializing the console (editor), I'm not seeing where the console history is ever initialized to anything beyond 0.  That fits the current circumstances (if console start is 0, then everything is read on the call to enter! from the editor).....

Note: using 'reload-selection' (can't find eval....and having trouble finding the keyboard shortcut for eval..) works fine.  Looking at the source, it makes sense, since it manually invokes the .onenter method from the bridge, and pushes in text that's pre-conditioned to work with a console-history at 0....
Subsequently trying to use the REPL goes back to the old (zeroed?) console start....which reverts to the compilation errors as the console tries to eval the preamble and repl-header...

**Comment by oakes** [comment]
See the `reset-console-start!` function, called at the end of `append-text!` via `reset-console-history!`.

**Comment by oakes** [comment]
Edited my previous comment with the correct function name.

**Comment by joinr** [comment]
I'm tracking now.  So you setup a pipes from clj/java->js  via (clj) nightcode.builders/pipe-into-console!, which - via a thread polling at 100ms intervals - invokes (cljs) nightcode.paren-soup/append on valid reads, which in turn invokes paren-soup/append-text! on the editor.  This should be causing updates to the console editor start as we go along.  So somewhere in that chain of causality, the editor is not realizing (or being initialized) that the console start has progressed beyond 0.  Is this looking like the right trail?   In other words, if things are working properly, I should be able to interrogate the console via some call to .executeScript on the webview, to scrape out the current value of :start on the console, and it should be positive after the repl is initialized?

**Comment by oakes** [comment]
That's right. Unfortunately this is quite hard to debug. I suppose you'd have to clone paren-soup, add a `(.log js/console ...)` call somewhere to log that value, run `boot local` in paren-soup to install it locally, change the paren-soup version in Nightcode's build.boot to match it, uncomment [this line](https://github.com/oakes/Nightcode/blob/master/resources/public/paren-soup.html#L30) so a Firebug pane appears inside all editor/console panes, and run `boot build-cljs` in Nightcode, then finally build the new jar using the mechanism you came up with. Oy! 😓 Theoretically, the resulting copy of Nightcode would display a little Firebug pane in the console (you'll definitely need to resize it to see the console itself) and then you should see your console.log calls. Not sure if you wanted to get this deeply into it, but I figured I'd try figuring out a debugging technique here.

**Comment by joinr** [comment]
I actually don't mind going down that route.  If you're around for a bit in near-realtime, and don't mind getting on #clojure on IRC freenode.net, I'd like to ask some architectural ?s so I can get my head straight [vs. writing a book on here].

**Comment by joinr** [comment]
For the record, the Sling-Blade solution to this problem was to update my JDK to 1.8.0_144, after which apparently a bug in the JavaFX WebEngine had been fixed.  I was running 111.  Keep your JDKs up to date.
This doesn't affect the boot-related build bug from issue 216.

**Comment by oakes** [comment]
FYI I just fixed the issue with building the JAR on Windows.
