### ISSUE TITLE
Linux bootstrap script possibly broken

### ISSUE THREAD

**Issue by wirepatch** [oakes/Nightcode#229]
https://raw.githubusercontent.com/paullucas/nightcode-bashscript/master/nightcode fails on user execution:

```
mistudent@w10m:~$ /tmp/nightcode 
wget: missing URL
Usage: wget [OPTION]... [URL]...
```

This is IMHO due to misplaced double quotes wrongly concatenating the URL part as well thus providing `"$HOME/nightcode/ https://github.com/oakes/Nightcode/releases/download/2.0.0/Nightcode-2.0.0.jar"` to become a `--directory-prefix` option argument. Instead the following works and is probably intended:

```
wget --directory-prefix="$HOME/nightcode/" https://github.com/oakes/Nightcode/releases/download/2.0.0/Nightcode-2.0.0.jar;
```

**Comment by oakes** [comment]
I do not maintain that script so I'm not sure how to fix it.
