### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by svdo** [oakes/Nightcode#257]
Hi,

Not an issue this time, just a bit of feedback about Nightcode. Yesterday evening I hosted a Clojure coding dojo for ~45 people who where mostly new to Clojure. When preparing, I had been looking for the best setup to use. VSCode, Atom, Cursive, etc. I wanted something that supports parinfer smart mode (because that gives by far the least friction to "newbies"). And I wanted something simple, simple to use and also important: simple to setup.

Nightcode ticks all of those boxes, and more! It was a very pleasant experience and the attendees were also very positive about it!

So this issue is just to say: THANK YOU! Nightcode is awesome and your efforts are greatly appreciated!!!

Best regards,

Stefan

**Comment by oakes** [comment]
That is fantastic to hear. As a former teacher i'm happy it's still being used for teaching!
