### ISSUE TITLE
Modified files and directories are not detected

### ISSUE THREAD

**Issue by kumarshantanu** [oakes/Nightcode#52]
When files are modified, added or deleted outside of Nightcode, those changes are not reflected in Nightcode UI. When I have unsaved changes in a file and the underlying content has been changed by another process, Nightcode should prompt me by asking whether I want to load the new version from file-system replacing the current buffer content. For unmodified files, it should reload them without asking the user.

**Comment by oakes** [comment]
I just released Nightcode 2.5.0 which finally adds this feature. Now I get to close the oldest open issue! =)
