### ISSUE TITLE
Improve performance of `lein` tasks

### ISSUE THREAD

**Issue by bruceadams** [oakes/Nightcode#56]
I'd like to get `lein` tasks to run faster. I am actively looking into how this might achieved. I'm very happy to hear anyone's thoughts, suggestions or concerns.

**Comment by oakes** [comment]
Nightcode uses Boot by default now, and I think it is faster at Leiningen tasks as well since the rewrite, so after nearly 3 years I'm assuming it's safe to close this issue now ;) Happy to re-open if anyone has noticed performance issues with build commands lately.
