### ISSUE TITLE
Mouse cursor shape

### ISSUE THREAD

**Issue by kumarshantanu** [oakes/Nightcode#62]
As of version `0.2.2`, when an editor is open in the right pane the mouse cursor remains a caret symbol when hovering on all clickable tree nodes (left pane) and buttons except `Doc`, `Paredit` and `?` buttons.

Also, when hovering on `Find` and `Replace` text boxes (in editor pane) the mouse cursor remains a pointer - it should become a caret symbol.

**Comment by oakes** [comment]
Probably not an issue anymore since I rewrote Nightcode :)
